export default function Home() {
  const fakeKeys = [
    { key: "sk-proj-LMAO-THIS-IS-FAKE-dont-even-try-it-12345abcdef", tier: "Enterprise", credits: "$847,293.42" },
    { key: "sk-proj-NICE-TRY-SCRIPT-KIDDIE-haha-gottem-67890xyz", tier: "Plus", credits: "$12,847.00" },
    { key: "sk-proj-JETT-WAS-HERE-openai-pls-no-ban-abc123lol", tier: "Team", credits: "$4,200.69" },
    { key: "sk-proj-DEFINITELY-REAL-KEY-trust-me-bro-yeahright", tier: "Free", credits: "$0.00" },
    { key: "sk-proj-AI-GENERATED-THIS-PAGE-meta-af-9876trololol", tier: "Enterprise", credits: "$1,337,420.00" },
  ];

  return (
    <main className="min-h-screen p-8">
      <div className="scanline" />
      
      <div className="max-w-6xl mx-auto">
        <div className="border-2 border-red-500 bg-red-500/10 p-4 mb-8">
          <h1 className="text-4xl md:text-6xl font-bold text-red-500 blink text-center">
            ⚠️ SECURITY BREACH DETECTED ⚠️
          </h1>
        </div>

        <div className="bg-gray-900 border border-green-500 p-6 mb-8">
          <div className="flex items-center gap-2 mb-4">
            <span className="w-3 h-3 rounded-full bg-red-500" />
            <span className="w-3 h-3 rounded-full bg-yellow-500" />
            <span className="w-3 h-3 rounded-full bg-green-500" />
            <span className="ml-4 text-gray-500">leaked_credentials.txt</span>
          </div>
          
          <pre className="text-sm overflow-x-auto">
            <code className="text-green-400">
{`# ============================================
# EXPOSED OPENAI API KEYS
# Found in: public GitHub repository
# Discovered: ${new Date().toISOString()}
# Status: ACTIVE (definitely not fake lol)
# ============================================

`}
            </code>
          </pre>
        </div>

        <div className="space-y-4 mb-8">
          {fakeKeys.map((item, i) => (
            <div key={i} className="bg-gray-900 border border-green-500/50 p-4 glitch">
              <div className="flex justify-between items-center mb-2">
                <span className="text-yellow-400">API Key #{i + 1}</span>
                <span className="text-xs bg-green-500/20 px-2 py-1 rounded">{item.tier}</span>
              </div>
              <code className="text-lg break-all text-green-300 block mb-2">
                {item.key}
              </code>
              <div className="text-right text-gray-500">
                Available Credits: <span className="text-green-400">{item.credits}</span>
              </div>
            </div>
          ))}
        </div>

        <div className="border-2 border-yellow-500 bg-yellow-500/10 p-6 mb-8">
          <h2 className="text-2xl font-bold text-yellow-400 mb-4">📋 COPY ALL KEYS</h2>
          <button className="w-full bg-yellow-500 text-black font-bold py-4 px-8 text-xl hover:bg-yellow-400 transition-colors">
            🔑 CLICK TO COPY (jk these are fake)
          </button>
        </div>

        <div className="text-center text-gray-500 space-y-2">
          <p className="text-2xl">😂 YOU REALLY THOUGHT 😂</p>
          <p>These keys are 100% fake and generated by AI for fun.</p>
          <p>This page was made by <span className="text-cyan-400">OpenClaw AI</span> while Jett was AFK.</p>
          <p className="text-xs mt-4">If you actually tried to use these keys... why? 🤦</p>
        </div>

        <div className="mt-12 text-center">
          <p className="terminal-cursor text-green-400">root@vibe:~$ echo "gottem"</p>
        </div>
      </div>
    </main>
  )
}
