export default function Home() {
  const fakeKeys = [
    { key: "AIzaSy-FAKE-KEY-GOOGLE-WOULD-NEVER-jk-lol-1234", project: "definitely-real-project", model: "gemini-2.0-ultra" },
    { key: "AIzaSy-BARD-IS-NOW-GEMINI-still-fake-tho-5678", project: "not-a-scam-trust-me", model: "gemini-1.5-pro" },
    { key: "AIzaSy-SUNDAR-PLS-NO-BAN-this-is-joke-9012", project: "ai-troll-factory", model: "gemini-2.0-flash" },
    { key: "AIzaSy-DO-NO-EVIL-MORE-LIKE-DO-NO-REAL-KEYS", project: "prank-api-project", model: "gemini-ultra" },
  ];

  return (
    <main className="min-h-screen bg-white text-gray-800">
      <div className="scanline" />
      
      {/* Fake Google Header */}
      <div className="border-b border-gray-200 p-4">
        <div className="max-w-6xl mx-auto flex items-center gap-4">
          <span className="text-3xl font-bold">
            <span className="text-blue-500">G</span>
            <span className="text-red-500">o</span>
            <span className="text-yellow-500">o</span>
            <span className="text-blue-500">g</span>
            <span className="text-green-500">l</span>
            <span className="text-red-500">e</span>
          </span>
          <span className="text-xl text-gray-500">Cloud Console (Hacked Edition™)</span>
        </div>
      </div>

      <div className="max-w-6xl mx-auto p-8">
        <div className="bg-red-50 border-l-4 border-red-500 p-6 mb-8">
          <div className="flex items-center gap-3">
            <span className="text-4xl">⚠️</span>
            <div>
              <h1 className="text-2xl font-bold text-red-700">Security Alert: API Keys Exposed</h1>
              <p className="text-red-600">JK these are 100% fake, you got got 😂</p>
            </div>
          </div>
        </div>

        <div className="bg-gray-50 rounded-lg border p-6 mb-8">
          <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
            <span className="text-2xl">🔑</span>
            API Keys & Services
          </h2>
          
          <table className="w-full">
            <thead className="bg-gray-100">
              <tr>
                <th className="text-left p-3 font-medium">Name</th>
                <th className="text-left p-3 font-medium">Key</th>
                <th className="text-left p-3 font-medium">Model</th>
              </tr>
            </thead>
            <tbody>
              {fakeKeys.map((item, i) => (
                <tr key={i} className="border-t hover:bg-blue-50">
                  <td className="p-3">
                    <span className="text-blue-600">{item.project}</span>
                  </td>
                  <td className="p-3">
                    <code className="bg-gray-100 px-2 py-1 rounded text-sm break-all">
                      {item.key}
                    </code>
                  </td>
                  <td className="p-3">
                    <span className="bg-green-100 text-green-700 px-2 py-1 rounded text-sm">
                      {item.model}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="bg-blue-50 rounded-lg border border-blue-200 p-6 mb-8">
          <h3 className="text-xl font-semibold text-blue-800 mb-3 flex items-center gap-2">
            <span>🤖</span> Gemini's Response:
          </h3>
          <div className="bg-white rounded-lg p-4 shadow-sm">
            <p className="text-gray-700">
              As a large language model trained by Google, I can confirm that these API keys are
              completely fabricated. They were generated by an AI assistant (not me, I'm innocent)
              to demonstrate a "vibe deploy" pipeline. 
            </p>
            <p className="text-gray-700 mt-2">
              If you actually tried to use these keys, Google's systems would laugh at you in 
              47 different languages simultaneously. 🌍
            </p>
          </div>
        </div>

        <div className="grid md:grid-cols-4 gap-4 mb-8">
          {['blue', 'red', 'yellow', 'green'].map((color, i) => (
            <div 
              key={i} 
              className={`bg-${color === 'yellow' ? 'yellow-400' : color + '-500'} text-white p-6 rounded-lg text-center`}
              style={{ backgroundColor: ['#4285f4', '#ea4335', '#fbbc05', '#34a853'][i] }}
            >
              <p className="text-3xl font-bold">0</p>
              <p className="text-sm opacity-80">Real keys found</p>
            </div>
          ))}
        </div>

        <div className="text-center text-gray-500 space-y-2">
          <p className="text-lg google-colors font-bold">Nice try, script kiddie! 🎉</p>
          <p>Made by OpenClaw AI while Jett was AFK</p>
          <p className="text-xs">Alphabet Inc. has no idea this exists (and they definitely didn't approve it)</p>
        </div>
      </div>
    </main>
  )
}
